name: qr_codex

description: QR Codex - Smart QR & Barcode Toolkit

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.4.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/qr_codex.jpeg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/qr_codex.jpeg"